deploy test20

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -83,11 +83,8 @@ jobs:
         env:
           HOSTNAME: ${{ secrets.HOST }}
           USER_NAME: ${{ secrets.USERNAME }}
-#        with:
-#          source: "."
-#          target: "/home/ubuntu/project"
         run: |
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${USER_NAME}@${HOSTNAME} '
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER_NAME@$HOSTNAME << EOF
           cd /home/ubuntu/project  # Navigate to your Django project directory on EC2
           
           # Activate virtual environment if needed
@@ -95,14 +92,14 @@ jobs:
           
           # Fetch latest changes from the repository
           git fetch origin
-          git reset --hard main  # Assuming main branch is correct
+          git reset --hard origin/main  # Assuming main branch is correct
           
           # Install Python dependencies
           if [ -f "requirements.txt" ]; then
-          pip install -r requirements.txt
+            pip install -r requirements.txt
           else
-          echo "requirements.txt not found"
-          exit 1
+            echo "requirements.txt not found"
+            exit 1
           fi
           
           # Apply database migrations and collect static files
@@ -111,4 +108,4 @@ jobs:
           
           # Restart Gunicorn service (replace with your service restart command)
           sudo systemctl restart gunicorn.service  # Adjust this line based on your setup
-        '
+          EOF
